# Etapa 1: Construção do projeto com Maven
FROM maven:3.8.3-openjdk-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src/ src/
RUN mvn clean package -DskipTests

# Etapa 2: Execução do projeto
FROM openjdk:21-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]